name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build_and_publish.yml"
      - "scripts/**"
      - "spark_conf/**"
      - "Dockerfile"

env:
  NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  docker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark-version:
          - {v: "3.1.3", arg: "v3.1.3"}
          - {v: "3.2.4", arg: "v3.2.4"}
          - {v: "3.3.3", arg: "3.3.3"}
          - {v: "3.4.1", arg: "3.4.1"}
          - {v: "3.5.0", arg: "3.5.0"}
          - {v: "latest", arg: "latest"}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        env:
          IMAGE_NAME: spark-delta-standalone
        with:
          push: true
          tags: ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ matrix.spark-version.v }}
          build-args: SPARK_VERSION=${{ matrix.spark-version.arg }}
