name: ci

on:
  push:
    branches:
      - "main"
    # paths:
    #   - "Dockerfile"

env:
  NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  docker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark-version:
          - "3.0.3"
          - "3.1.3"
          - "3.2.4"
          - "3.3.3"
          - "3.4.1"
          - "3.5.0"
          - "latest"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        env:
          IMAGE_NAME: spark-delta-standalone
        with:
          push: true
          tags: ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ matrix.spark-version }}
